
INSERT INTO DEPENDENT VALUES (1,'Salvatore','Di Costanzo',12000);
INSERT INTO DEPENDENT VALUES (2,'Emanuele','Iandolo',12000);
INSERT INTO DEPENDENT VALUES (3,'Mario','Rossi',12000);
INSERT INTO DEPENDENT VALUES (4,'Giuseppe','Bianchi',12000);
INSERT INTO DEPENDENT VALUES (5,'Maurizio','Cirillo',12000);
