
INSERT INTO DEPENDENT VALUES (1,'Di Costanzo','Salvatore',12000);
INSERT INTO DEPENDENT VALUES (2,'Iandolo','Emanuele',12000);
INSERT INTO DEPENDENT VALUES (3,'Rossi','Mario',12000);
INSERT INTO DEPENDENT VALUES (4,'Bianchi','Giuseppe',12000);
INSERT INTO DEPENDENT VALUES (5,'Cirillo','Maurizio',12000);